#-------------------------------
# General Site Settings

title: Artists Theme
description: Thinker // Designer // YouTuber
email: devtipsfordesigners@gmail.com

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: Me, url: '#me'}
- {name: Projects, url: '#projects'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Provide a description for your website to make it visible to search engines.'
  rel-author: 'https://plus.google.com/u/0/+DevTipsForDesigners/'
  rel-publisher: 'https://plus.google.com/u/0/+DevTipsForDesigners/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section



#-------------------------------
# Projects Section

projects:
- {name: MyProject 1, folder: 'project1'}
- {name: MyProject 2, folder: 'project2'}
- {name: MyProject 3, folder: 'project3'}
- {name: MyProject 4, folder: 'project4'}
- {name: MyProject 5, folder: 'project5'}
- {name: MyProject 6, folder: 'project6'}
- {name: MyProject 7, folder: 'project7'}
- {name: MyProject 8, folder: 'project8'}



#- {name: Project 2, folder: 'proj-2', file: 'work/proj-2.html'}
#- {name: Project 3, folder: 'proj-3', file: 'work/proj-3.html'}
#- {name: Project 4, folder: 'proj-4', file: 'work/proj-4.html'}
#- {name: Project 5, folder: 'proj-5', file: 'work/proj-5.html'}
#- {name: Project 6, folder: 'proj-6', file: 'work/proj-6.html'}
#- {name: Project 7, folder: 'proj-7', file: 'work/proj-7.html'}
#- {name: Project 8, folder: 'proj-8', file: 'work/proj-8.html'}




#-------------------------------
# Clients Section

clients:
- {avatar: 'face-aaroni.jpg',
  name: 'Scott Summers',
  title: 'Director of Design, OnToText Ind.',
  quote: '<p><strong>While we all felt that Travis was a great</strong> asset to our team — and really worked hard to understand our products from the point of view of the customer — we also all agree he should shower more often.</p>',
  logo: 'logo1.png'}
- {avatar: 'face-atariboy.jpg',
  name: 'Hank McCoy',
  title: 'Eater of Salad, Antartica Int.',
  quote: '<p><strong>Working with Travis was the highlight of my career.</strong> Other moments of note were collecting the largest number of paperclips in the office, and winning a trophy for saying "uh huh, and then what?" 30 times in a row to my girlfriend without her noticing.</p>',
  logo: 'logo2.png'}
- {avatar: 'face-jackiesaik.jpg',
  name: 'Stacy Lang',
  title: 'Social Media Girl, Quebec Int.',
  quote: '<p><strong>Yea, I guess hes good at computers or something,</strong> but let me ask you this: If a cat always lands on its feet, and buttered bread always lands butter side down, what would happen if you tied buttered bread on top of a cat?</p>',
  logo: 'logo3.png'}
- {avatar: 'face-teleject.jpg',
  name: 'Cleatus Cassidy',
  title: 'VP of Helmut, Lorem Sorem LLC.',
  quote: '<p><strong>Back in old country</strong> only nerds who is playing on computers. Now all bros is wanting to make codes and junk. I lost foot in war. You dont see girls asking me about homework.</p>',
  logo: 'logo4.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'http://twitter.com/devtipsshow'}
- {icon: 'dribbble', link: 'https://dribbble.com/travisneilson'}
- {icon: 'behance', link: 'https://www.behance.net/travisneilson'}
- {icon: 'youtube', link: 'https://www.youtube.com/DevTipsForDesigners'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travisneilson/'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
